nelmio_api_doc:
    documentation:
        info:
            title: Api Doc
            description: Quelle incroyable Api !
            version: 1.0.0

    models:
        names:
            - { alias: User_admin_read,  type: App\Entity\User, groups: [ admin:read ] }
            - { alias: User_admin_write,  type: App\Entity\User, groups: [ admin:write ] }
            - { alias: User_read,  type: App\Entity\User, groups: [ user:read ] }
            - { alias: User_update,  type: App\Entity\User, groups: [ update ] }


    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc