security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

#    encoders:
#        App\Entity\User:
#            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
                    - lexik_jwt_authentication.jwt_token_authenticator
#                entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout

            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

            switch_user: true
            entry_point: App\Security\LoginFormAuthenticator

    role_hierarchy:
        ROLE_DEVELOPER: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_ADMIN: ROLE_USER

    access_control:
         - { path: ^/api/login_check,        roles: PUBLIC_ACCESS }
         - { path: ^/api/users/password,     roles: PUBLIC_ACCESS }
         - { path: ^/api/contact,            roles: PUBLIC_ACCESS }
         - { path: ^/api,                    roles: ROLE_USER }
         - { path: ^/admin,                  roles: ROLE_ADMIN }
